= Introduction to TechInTen
:page-slug: introduction
:figure-caption!:

TechInTen is a community-driven way to teach technology and best practices in ten minutes or less via brief video and AsciiDoc content.
It is used by knowledge workers to share nuggets of knowledge with partner teams in sales, marketing, and training and with customers directly via the TechInTen site.

== Develop easy to learn intro's to key technolofy and best practices

As a developer contributing to TechInTen you can quickly capture new knowledge as you learn it and make it available for the broader community.

== The TechInTen contributor experience

Just author notes and link to video content via ASCIIDOC documents and comit them to the GIT repo. The docs will be converted to HTML using Gatsby and served up to the TechInTen site via GITHUB Pages.

Get going quickly ::
+
To accelerate your development project, TechInTen provides developer scaffolds and apps with open-source code as starting points.
Simply fork one of these apps and start editing the code.
Leverage and learn about TechInTen technology ::
+
API Management lets you ... ::
+
The TechInTen platform has built-in infrastructure to handle your knowledge packaging and deployment.
You get integrated source control, development and staging environments, preview and debugging tools, a CI pipeline, hosting, and more.
Distribute your knowledge to a marketplace ::
+
Reach a vibrant community of content creators and knowledge consumers by adding your knowledge to TechInTen.


== Get started

For help in writing your first post with TechInTen, check out these resources:

* <<start-tutorial#>> – Step-by-step tutorial for learning fundamental concepts and developing your first project on Koji.
* <<withkoji-koji-core#>> – Package reference for implementing core platform features in your apps.
* https://withkoji.com/create/for-developers[Developer scaffolds in the Template Store] – Starting points for an entirely new web app on Koji.

== What's new for developers

For the latest updates to the Koji platform, packages, and developer site, check out the <<developer-updates#>>.

== Stay in touch

* Join the SLACK channel on Slack to connect with other developers, creators, and the TechInTen team.
The community is the best place to share tips and tricks, provide peer feedback, and get support.
* Check out ____ for answers to general questions about TechInTen or visit the TechInTen Support page to log an issue or request.
* Contribute to the developer site by coding, writing new articles, or suggesting edits to existing documentation.
* Subscribe to the knowledge worker email list to keep up with the latest announcements, featured content, events, and developer programs.
